# swagger API 설정
springdoc:
  api-docs:
    path: /api-docs/v1
    version: openapi_3_0
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha
    groups-order: desc
    operations-sorter: method
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-match:
    - /**

# H2-console 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/traveldb
    username: user
    password: user1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # sql 쿼리 콘솔 출력 허용
    hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show_sql: true
    properties:
      hibernate:
        # SQL 쿼리에 주석을 추가하여 해당 쿼리가 어떤 Hibernate 쿼리에 해당하는지 식별
        use_sql_comments: false
        # 쿼리 포멧팅
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false



# kakao map api
kakao:
  api-url: https://dapi.kakao.com/v2/local/search/address.json
  api-key: 4f403450685d85faea564f42eb536736
