version: "3"
services:
  db:
    build:
      context: ./docker-mysql # Dockerfile내부에서 탐색할 경로의 컨텍스트 설정
      dockerfile: DockerFile
    restart: always
    ports:
      - "3307:3306"	# mysql 기본 port
    environment:
      MYSQL_ROOT_PASSWORD: user1234
      MYSQL_DATABASE: traveldb
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      TZ: Asia/Seoul
    volumes:
      - ./docker-mysql/mysql/data:/var/lib/mysql
      - ./docker-mysql/mysql/config:/etc/mysql/conf.d
      - ./docker-mysql/mysql/init:/docker-entrypoint-initdb.d